Map<String, String> ge = {
  //LoginScreen
  'title_login': 'Hey, melde dich jetzt an',
  'email_phone': 'E-Mail oder Telefonnummer',
  'password': 'Passwort',
  'forget_password': 'Passwort vergessen?',
  'login_now': 'Jetzt einloggen',
  'are_you_new': 'Bist du neu?',
  'register_now': 'Jetzt registrieren',

  //RegisterScreen
  'title_register': 'Ein neues Konto erstellen',
  'your_name': 'Ihren Namen',
  'email': 'Email',
  'phone_number': 'Telefonnummer',
  'confirm_password': 'Bestätige das Passwort',
  'refer_code': 'Siehe Code',
  'optional': '(Optional)',
  'are_already_user': 'Sind Sie bereits Benutzer?',
  'mobile_number_must_10_digit' : 'Die Handynummer muss 10-stellig sein',
  'retry':'Wiederholen',

  //ForgotPasswordScreen
  'forgot_password': 'Passwort vergessen',
  'send_otp': 'OTP SENDEN',

  //OtpScreen
  'enter_otp': 'OTP eingeben',
  'verified': 'Verifiziert',
  'not_get': 'Nicht bekommen?',
  're_send': ' Erneut senden',
  're_send_otp': 'Otp erneut senden',

  //NewPasswordScreen
  'create_new_password': 'Neues Passwort erstellen',
  're_type_password': 'Passwort wiederholen',
  'save': 'Speichern',

  //DeshboardScreen
  'deshboard': 'Schreibtisch',
  'search': 'Suchen',
  'unverified': 'Unbestätigt',
  'booking_accepting': 'Buchungsannahme',

  //EventCategoryScreen
  'submit': 'Einreichen',
  'add_event': 'Ereignis hinzufügen',
  'what_event_name': 'Wie heißt die Veranstaltung?',
  'what_event_type': 'Was ist der Ereignistyp?',
  'b2b': 'B2B',
  'public_party': 'Öffentliche Partei',
  'other': 'Andere',

  //EventTimesScreen
  'select_start_date_end': 'Start- und Enddatum auswählen',
  'back': 'Zurück',
  'next': 'Nächste',
  'create_new_event': 'Neues Ereignis erstellen',
  'can_know_date': 'Kann ich die Daten erfahren?',
  'start_time': 'Startzeit',
  'end_time': 'Endzeit',
  'event_description': 'Was ist die Ereignisbeschreibung?',
  'select_date': 'Datum auswählen',

  //EventSettingListScreen
  'select_any': 'Wählen Sie Beliebig aus',
  'let_create_it': 'Lassen Sie es uns erstellen!',
  'no_of_table': 'Nr. der Tabelle',
  'no_of_person': 'Nr. der Person',
  'price_table': 'Preisliste',
  'table': 'Tisch',
  'chair': 'Stuhl',
  'sofa': 'Sofa',
  'booth': 'Verkaufsstand',
  'stands': 'Steht',
  'add_details': 'Einzelheiten hinzufügen',
  'vettical_location': 'Vetical Lage',
  'horizontal_location': 'Horizontale Position',
  'top': 'Spitze',
  'center': 'Center',
  'bottom': 'Unterseite',
  'none': 'Keiner',
  'left': 'Links',
  'right': 'Rechts',
  'per_table_capacity': 'Pro Tisch Terson Kapazität',
  'total_person_capacity': 'Gesamtpersonenkapazität',
  'per_table_price': 'Preis pro Tisch',
  'per_person_price': 'Preis pro Person',
  'total_amount': 'Gesamtmenge',
  'veg': 'Gemüse',
  'non_veg': 'Nicht vegetarisch',
  'both': 'Beide',
  'non': 'Nicht',
  'select_food':'Essen auswählen',
  'food_dexcription': 'Lebensmittelbeschreibung?',
  'select_Equipment': 'Ausrüstung auswählen',
  'equipment': 'Ausrüstung',
  'equipment_description': 'Gerätebeschreibung?',
  'select_item': 'Menüpunkt wählen',
  'language_and_currency': 'Sprache und Währung',
  'add_cate' : 'Hinzufügen',

  //EventGalleryScreen
  'maximum_fifteen_images_upload': 'Maximal 15 Bilder hochladen',
  'select_poster': 'Wählen Sie Plakat',
  'add_poster': 'Poster hinzufügen',
  'add_video': 'Video hinzufügen',
  'add_poster_15': 'Fotos hinzufügen (max. 15)',
  'remove': 'ENTFERNEN',
  'max_60min_video': 'Maximal 60 Minuten für 1 Video',

  //EventPermissionLetterScreen
  'permission_verfication': 'Genehmigungsschreiben zur Überprüfung',
  'attached_pdf_only': 'Nur angehängtes pdf',
  'accept_booking': 'Buchung akzeptieren',
  'accept_booking_des':
  'Deaktivieren Sie es, wenn Sie das Ereignis nur anzeigen möchten,\nund es dem Benutzer nicht erlauben, es zu buchen',
  'des_1': 'Für jedes verkaufte Ticket werden 5 % Provision + GST ​​berechnet',
  'des_2': 'Wenn der Preis des Tickets 0 beträgt, wird keine Provision\nberechnet',

  //EventDiscountScreen
  'discount_total_bill': 'Rabatt auf Gesamtrechnung',
  'cancel': 'STORNIEREN',
  'apply': 'ANWENDEN',

  //EventAddressScreen
  'flat_no': 'Wohnung Nr.',
  'street_name': 'Straßenname.',
  'area_name': 'Bereichsname.',
  'city': 'Stadt',
  'state': 'Zustand',
  'what_the_location': 'Was ist der Standort?',
  'type_here_address': 'Geben Sie hier Adresse ein...',
  'location_from_google_map': 'Standort von Google Map',

  //EventCompanyDetailsScreen
  'maximum_one_video_upload': 'Maximal ein Video-Upload',
  'let_create_the_event': 'Lassen Sie uns das Ereignis erstellen',
  'company_name': 'Name der Firma',
  'company_gst': 'GST des Unternehmens (optional)',
  'upload_pdf': 'PDF hochladen',
  'company_contact_no': 'Firma Kontakt Nr',
  'company_email': 'Firmen-E-Mail',
  'about_our_company': 'Über unsere Firma',
  'address': 'Adresse',
  'pincode': 'Geheimzahl.',
  'add_photo_max_05': 'Fotos hinzufügen (max. 05)',
  'add_video_max_01': 'Video hinzufügen (max. 01)',

  //EventPersonalDetailsScreen
  'full_name_mr': 'Vollständiger Name (Herr / Frau / Frau)',
  'mobile_number': 'Handy Nummer',
  'alternative_mobile_number': 'Alternative Handynummer (optional)',
  'email_address': 'E-Mail-Addresse',

  //EventSocialMediaScreen
  'terms_and_condition': 'Geschäftsbedingungen',
  'social_media': 'Sozialen Medien',
  'accept_terms_and_condition': 'Akzeptieren Sie Ihre Allgemeinen Geschäftsbedingungen',
  'live_this_event': 'Lebe dieses Ereignis?',

  //CookingTogetherScreen
  'cooking_together': 'Gemeinsam kochen',
  'overview': 'ÜBERBLICK',
  'attendee': 'TEILNEHMER',
  'review': 'REZENSION',

  //OverviewFragment
  'sold': 'Verkauft :',
  'unsold': 'Unverkauft :',
  'check': 'ÜBERPRÜFEN',
  'food_description': 'Lebensmittelbeschreibung',
  'photo_video_gallery': 'Foto- und Videogalerie',
  'ticket': 'Fahrkarte',
  'price': 'Preis',
  'show_all': 'Zeige alles',

  //ShopFragment
  'shop_offer': 'Shop-Angebot',
  'online_offer': 'Online-Angebot',
  'add_your_shop': 'Fügen Sie Ihren Shop hinzu',
  'create_offer': 'Angebot erstellen',

  //ShopAddScreen
  'continue': 'WEITERMACHEN',
  'let_add_shop': 'Lassen Sie uns Shop hinzufügen!',
  'select_category': 'Kategorie wählen',
  'shop_name': 'Laden Name',
  'shop_day': 'Shop-Tag',
  'about_us': 'Über uns',
  'social_media_link': 'Social-Media-Links',

  //ShopDetailsScreen
  'edit':'Bearbeiten',
  'show':'Zeigen',
  'delete':'Löschen',
  'about_shop':'Über Laden',

  //OfferAddScreen
  'person':'Person',
  'percentage':'Prozentsatz',
  'description':'Beschreibung',
  'image_add':'Bild\nhinzufügen',
  'add_products_name':'Produktnamen hinzufügen',
  'let_make_it':'Lass es uns machen',
  'what_my_name':'Was ist mein Name? (Hauptangebotsname)',
  'offer_product':'Angebot auf Produkt',
  'all':'Alle',
  'specific':'Spezifisch',
  'image':'Bild',
  'add':'+ Hinzufügen',
  'unlimited':'Unbegrenzt',
  'select_gallery':'Galerie auswählen',
  'select_camera':'Wählen Sie Kamera',
  'video':'Video',

  //SideMenuScreen
  'my_subscription':'Mein Abonnement',
  'current_subscription':'Aktuelles Abonnement',
  'refer_earn':'Empfehlen und verdienen',
  'notification':'Benachrichtigung',
  'redeem':'Tilgen',
  'help_faq':'Hilfe & FAQ',
  'entertainment':'Unterhaltung',
  'our_product':'Unser Produkt',
  'history':'Geschichte',
  'event_offers':'Meine Veranstaltung & Angebote',
  'you_have':'Du hast',
  'log_out':'AUSLOGGEN',
  'redeem_coin':'Münze einlösen',
  'redeem_your_coin':'Lösen Sie Ihre Münze ein',
  'redeem_des':'Ihnen werden 5 % des eingelösten Betrags (\$12,35) in Rechnung gestellt.',
  'enter_upi_id':'Geben Sie Ihre Upi-ID ein',
  'upi_id':'UPI-ID',
  'coin_redeem':'Münze einlösen',
  'processing':'wird bearbeitet',
  'login_refer':'Login Refer',
  'coin_send':'Münze senden',
  'subcription_des':'Sie haben kein aktives Abonnement',
  'buy_now':'KAUFE JETZT',

  //BuySubscriptionScreen
  'local_offer_month':'Lokales\nAngebot Monatlich',
  'event_subscription':'Ereignis\nAbonnement',
  'live_stream_subscription':'Live-Stream\nAbonnement',
  'sub_des':'Es können 4 Events gepostet werden oder ein Event mit max. 30 Tagen',

  //MyEventOfferScreen
  'my_event_offers':'Meine Veranstaltungen & Angebote',
  'event':'Veranstaltungen',
  'offers':'Bietet an',

  //ReferAndEarnScreen
  'total_rewards_earned' : 'Gesamtzahl verdienter Prämien',
  'refer_friends_earn' : 'Verweisen Sie auf Ihre Freunde\nund verdienen Sie',
  'refer_get_coin' : 'Empfehlen und 10 Münzen erhalten',
  'refer_earn_desc' : 'Empfehlen Sie einen Freund und erhalten Sie zusätzlich 10 Münzen und Ihr Freund erhält zusätzlich 10 Punkte',
  'referral_code' : 'Referenzcode',
  'copy_code' : 'Kopieren\nCode',
  'share_refer_code' : 'Teilen Sie Ihren Empfehlungscode per',

  //HelpAndFaqScreen
  'help' : 'Hilfe',
  'faq' : 'FAQ',
  'evento_package' : 'Evento-Paket',
  'friends_fields':'Freundesfelder',
  'fcoin':'F-Coin',
  'festum_ads_mdia':'Festum-Werbemittel',
  'evento_des' : 'Es gibt viele Variationen von Passagen von Lorem Ipsum, aber die Mehrheit wurde in irgendeiner Form verändert, durch eingespritzten Humor oder zufällige Wörter, die nicht einmal annähernd glaubwürdig aussehen.',

  //OnlineOfferAddScreen
  'choose_media_select':'Wählen Sie Medien zur Auswahl aus',
  'from_gallery':'Aus der Galerie',
  'from_camera':'Von der Kamera',
  'online_shop_name':'Online-Shop-Name',
  'offer':'Angebot',
  'product_name':'Produktname',
  'add_offer_product_image':'Angebotsproduktbild hinzufügen',
  'product_description':'Produktbeschreibung',
  'select_platform_product_link':'Plattform & Produktlink auswählen',
  'all_platform':'Alle Plattform',

  //AddLiveStreamScreen && SocialMedia
  'maximum_two_video_upload':'Maximal zwei Video-Uploads',
  'create_live_stream':'Livestream erstellen',
  'event_name':'Veranstaltungsname',
  'event_category':'Ereigniskategorie',
  'event_des':'Eventbeschreibung',
  'event_date':'Veranstaltungsdatum',
  'event_type':'Ereignistyp',
  'free_for_user':'Kostenlos für Benutzer',
  'paid_for_user':'Bezahlt für Benutzer',
  'join_live_streaming_price':'Nehmen Sie am Live-Streaming-Preis teil',
  'per_user':'Pro/Benutzer',

  //MyEventAndOffers
  'view_invoice':'RECHNUNG ANZEIGEN',
  'withdraw_amount':'Betrag beheben',
  'invoice':'Rechnung',
  'invoice_no':'Rechnungsnummer:',
  'total_ticket_book':'Gesamtticket gebucht',
  'sub_total':'Zwischensumme',
  'commission':'Provision (5%)',
  'gst':'MwSt',
  'payable_amount':'Zu zahlender Betrag',
  'download_invoice':'Download Rechnung',

  'enter_select_date':'Geben Sie Datum auswählen ein',
  'enter_event_description':'Ereignisbeschreibung eingeben',
  'enter_product_description':'Produktbeschreibung eingeben',
  'enter_product_name':'Geben Sie den Produktnamen ein',
  'enter_online_shop_name':'Geben Sie den Namen des Onlineshops ein',
  'enter_email_number': 'Bitte E-Mail oder Telefonnummer eingebenr',
  'enter_password': 'Bitte geben Sie Ihr Passwort ein',
  'enter_your_name': 'Bitte geben Sie Ihren Namen ein',
  'enter_your_email': 'Bitte geben Sie ihre E-Mail-Adresse ein',
  'enter_your_phone_number': 'Bitte geben sie ihre Telefonnummer ein',
  'enter_your_confirm_password': 'Bitte geben Sie Ihr Bestätigungspasswort ein',
  'enter_your_refer_code': 'Bitte geben Sie Ihren Code ein',
  'enter_re_type_password': 'Geben Sie Ihr Wiederholungspasswort ein',
  'enter_event_name': 'Geben Sie den Ereignisnamen ein',
  'enter_other': 'Geben Sie Andere ein',
  'enter_start_time': 'Geben Sie die Startzeit ein',
  'enter_end_time': 'Endzeit eingeben',
  'enter_description': 'Beschreibung eingeben',
  'enter_discount_total_bill': 'Geben Sie den Rabatt auf die Gesamtrechnung ein',
  'enter_terms_and_condition': 'Allgemeine Geschäftsbedingungen eingeben',

  'enter_flat_no': 'Wohnungsnummer eingeben',
  'enter_street_name': 'Geben Sie den Straßennamen ein',
  'enter_area_name': 'Geben Sie den Bereichsnamen ein.',
  'enter_city': 'Stadt betreten',
  'enter_state': 'Staat eingeben',
  'enter_pincode': 'Geben Sie den PIN-Code ein.',
  'enter_compuny_name': 'Geben Sie den Firmennamen ein',
  'enter_company_contact_no': 'Geben Sie die Firmenkontaktnummer ein',
  'enter_company_email': 'Geben Sie die Firmen-E-Mail ein',
  'enter_about_our_company': 'Geben Sie Über unser Unternehmen ein',
  'enter_full_name_mr': 'Vollständigen Namen eingeben (Herr / Frau / Frau)',
  'enter_mobile_number': 'Handynummer eingeben',
  'enter_alternative_mobile_number': 'Geben Sie die alternative Handynummer ein',
  'enter_email_address': 'E-Mail Adresse eingeben',
  'enter_shop_name': 'Shop-Name eingeben',
  'enter_about_us': 'Geben Sie Über uns ein',
  'enter_offer_name': 'Geben Sie den Angebotsnamen ein',
  'enter_no_of_table': 'Geben Sie die Tischnummer ein',
  'enter_per_table_capacity': 'Geben Sie die Terson-Kapazität pro Tisch ein',
  'enter_total_person_capacity': 'Geben Sie die Gesamtpersonenkapazität ein',
  'enter_per_table_price': 'Geben Sie den Preis pro Tisch ein',
  'enter_per_person_price': 'Geben Sie den Preis pro Person ein',
  'enter_total_amount': 'Geben Sie den Gesamtbetrag ein',
  'enter_equipment_description': 'Gerätebeschreibung eingeben?',
  'enter_food_description': 'Geben Sie die Lebensmittelbeschreibung ein',

  'enter_facebook_link': 'Geben Sie den Facebook-Link ein',
  'enter_twitter_link': 'Geben Sie den Twitter-Link ein',
  'enter_instagram_link': 'Geben Sie den Instagram-Link ein',
  'enter_youtube_link': 'Youtube-Link eingeben',
  'enter_pintrest_link': 'Pintrest-Link eingeben',
  'enter_linkdin_link': 'Geben Sie den Linkdin-Link ein',
};
