Map<String, String> hi = {
  //LoginScreen
  'title_login': 'नमस्ते, अभी लॉग इन करें',
  'email_phone': 'ईमेल या फोन नंबर',
  'password': 'पासवर्ड',
  'forget_password': 'पासवर्ड भूल गए?',
  'login_now': 'अभी लॉगिन करें',
  'are_you_new': 'क्या आप नए हैं? ',
  'register_now': 'अभी पंजीकरण करें',

  //RegisterScreen
  'title_register': 'एक नया खाता बनाएं',
  'your_name': 'अप का नाम',
  'email': 'ईमेल',
  'phone_number': 'फ़ोन नंबर',
  'confirm_password': 'पासवर्ड की पुष्टि कीजिये',
  'refer_code': 'कोड देखें',
  'optional': '(वैकल्पिक)',
  'are_already_user': 'क्या आप पहले से ही उपयोगकर्ता हैं?',
  'mobile_number_must_10_digit' : 'मोबाइल नंबर 10 अंकों का होना चाहिए',
  'retry':'पुन: प्रयास करें',

  //ForgotPasswordScreen
  'forgot_password': 'पासवर्ड भूल गए',
  'send_otp': 'ओटीपी भेजें',

  //OtpScreen
  'enter_otp': 'ओटीपी दर्ज करें',
  'verified': 'सत्यापित',
  'not_get': 'नहीं मिलता?',
  're_send': ' पुन: संदेश',
  're_send_otp': 'ओटीपी पुनः भेजें',

  //NewPasswordScreen
  'create_new_password': 'नया पासवर्ड बनाएं',
  're_type_password': 'पासवर्ड फिर से लिखें',
  'save': 'बचाना',

  //Deshboard
  'deshboard': 'डैशबोर्ड',
  'search': 'खोज',
  'unverified': 'असत्यापित',
  'booking_accepting': 'बुकिंग स्वीकार करना',

  //EventCategoryScreen
  'submit' : 'जमा करना',
  'add_event' : 'कार्यक्रम जोड़ें',
  'what_event_name' : 'इवेंट का नाम क्या है?',
  'what_event_type' : 'इवेंट किस तरह का है?',
  'b2b' : 'बी2बी',
  'public_party' : 'सार्वजनिक पार्टी',
  'other' : 'अन्य',

  //EventTimesScreen
  'select_start_date_end':'प्रारंभ और समाप्ति तिथि का चयन करें',
  'back':'पीछे',
  'next':'अगला',
  'create_new_event':'नया ईवेंट बनाएँ',
  'can_know_date':'क्या मैं तारीखें जान सकता हूँ?',
  'start_time':'समय शुरू',
  'end_time':'अंत समय',
  'event_description':'घटना का विवरण क्या है?',
  'select_date':'तारीख़ चुनें',

  //EventSettingListScreen
  'select_any' : 'कोई भी चुनें',
  'let_create_it' : 'आइए इसे बनाएं!',
  'no_of' : 'टेबल की संख्या',
  'no_of_person' : 'व्यक्ति की संख्या',
  'price_table' : 'मूल्य / तालिका',
  'table': 'मेज',
  'chair': 'कुर्सी',
  'sofa': 'सोफ़ा',
  'booth': 'बूथ',
  'stands': 'खड़ा',
  'add_details': 'विवरण जोड़ें',
  'vettical_location': 'वेटिकल स्थान',
  'horizontal_location': 'क्षैतिज स्थान',
  'top': 'ऊपर',
  'center': 'केंद्र',
  'bottom': 'तल',
  'none': 'कोई नहीं',
  'left': 'बाएं',
  'right': 'सही',
  'per_table_capacity': 'प्रति टेबल टरसन क्षमता',
  'total_person_capacity': 'कुल व्यक्ति क्षमता',
  'per_person_price': 'प्रति व्यक्ति मूल्य',
  'total_amount': 'कुल राशि',
  'veg': 'शाकाहारी',
  'non_veg': 'मांसाहारी',
  'both': 'दोनों',
  'non': 'गैर',
  'select_food':'भोजन चुनें',
  'food_dexcription': 'भोजन का विवरण?',
  'select_Equipment': 'उपकरण का चयन करें',
  'equipment': 'उपकरण',
  'equipment_description': 'उपकरण विवरण?',
  'select_item': 'वस्तु चुनें',
  'photo_video_gallery': 'फोटो वीडियो गैलरी',
  'language_and_currency': 'भाषा और मुद्रा',
  'add_cate' : 'जोड़ना',

  //EventAddressScreen
  'flat_no':'नीरस नहीं।',
  'street_name':'सड़क का नाम।',
  'area_name':'क्षेत्र का नाम।',
  'city':'शहर',
  'state':'राज्य',
  'what_the_location':'स्थान क्या है?',
  'type_here_address':'यहां टाइप करें पता...',
  'location_from_google_map':'गूगल मैप से लोकेशन',

  //EventGalleryScreen
  'maximum_fifteen_images_upload': 'अधिकतम पंद्रह चित्र अपलोड',
  'select_poster': 'पोस्टर का चयन करें',
  'add_poster': 'पोस्टर जोड़ें',
  'add_video': 'वीडियो जोड़ें',
  'add_poster_15': 'तस्वीरें जोड़ें (अधिकतम 15)',
  'remove': 'निकालना',
  'max_60min_video': 'अधिकतम 60min 1 वीडियो के लिए',

  //EventPermissionLetterScreen
  'permission_verfication': 'सत्यापन के लिए अनुमति पत्र',
  'attached_pdf_only': 'केवल संलग्न पीडीएफ',
  'accept_booking': 'बुकिंग स्वीकार करें',
  'accept_booking_des':
  'यदि आप केवल ईवेंट दिखाना चाहते हैं\nऔर उपयोगकर्ता को इसे बुक करने की अनुमति नहीं \nदेना चाहते हैं तो इसे अचयनित करें',
  'des_1': 'बेचे गए प्रत्येक टिकट के लिए 5% कमीशन + जीएसटी\nशुल्क लिया जाएगा',
  'des_2': 'अगर टिकट की कीमत 0 है तो कोई कमीशन नहीं लिया जाएगा',

  //EventDiscountScreen
  'discount_total_bill':'कुल बिल पर छूट',
  'cancel':'रद्द करना',
  'apply':'आवेदन करना',

  //EventCompanyDetailsScreen
  'maximum_one_video_upload':'अधिकतम एक वीडियो अपलोड',
  'let_create_the_event':'आइए इवेंट बनाएं',
  'company_name':'कंपनी का नाम',
  'company_gst':'कंपनी जीएसटी (वैकल्पिक)',
  'upload_pdf':'पीडीएफ अपलोड करें',
  'company_contact_no':'कंपनी संपर्क संख्या',
  'company_email':'कंपनी ईमेल',
  'about_our_company':'हमारी कंपनी के बारे में',
  'address':'पता',
  'pincode':'पिन कोड',
  'add_photo_max_05':'तस्वीरें जोड़ें (अधिकतम 05)',
  'add_video_max_01':'वीडियो जोड़ें (अधिकतम 01)',

  //EventPersonalDetailsScreen
  'full_name_mr':'पूरा नाम (श्री / श्रीमती / सुश्री)',
  'mobile_number':'मोबाइल नंबर',
  'alternative_mobile_number':'वैकल्पिक मोबाइल नंबर (वैकल्पिक)',
  'email_address':'मेल पता',

  //EventSocialMediaScreen
  'terms_and_condition':'नियम और शर्तें',
  'social_media':'सामाजिक मीडिया',
  'accept_terms_and_condition':'अपने नियम और शर्तें स्वीकार करें',
  'live_this_event':'लाइव इस घटना?',

  //CookingTogetherScreen
  'cooking_together':'एक साथ खाना बनाना',
  'overview':'अवलोकन',
  'attendee':'प्रतिभागी',
  'review':'समीक्षा',

  //OverviewFragment
  'sold' : 'बिका हुआ :',
  'unsold' : 'नहीं बिका :',
  'check' : 'जाँच करना',
  'food_description' : 'भोजन विवरण',
  'ticket' : 'टिकट',
  'price' : 'कीमत',
  'show_all' : 'सब दिखाएं',

  //ShopFragment
  'shop_offer': 'दुकान प्रस्ताव',
  'online_offer': 'ऑनलाइन ऑफर',
  'add_your_shop': 'अपनी दुकान जोड़ें',
  'create_offer': 'प्रस्ताव बनाएँ',

  //ShopAddScreen
  'continue': 'जारी रखना',
  'let_add_shop': 'चलो दुकान जोड़ें!',
  'select_category': 'श्रेणी चुनना',
  'shop_name': 'दुकान का नाम',
  'shop_day': 'दुकान दिवस',
  'about_us': 'हमारे बारे में',
  'social_media_link': 'सोशल मीडिया लिंक्स',

  //ShopDetailsScreen
  'edit':'संपादन करना',
  'show':'दिखाना',
  'delete':'मिटाना',
  'about_shop':'दुकान के बारे में',

  //OfferAddScreen
  'person':'व्यक्ति',
  'percentage':'को प्रतिशतता',
  'description':'विवरण',
  'image_add':'चित्र\nजोड़ें',
  'add_products_name':'उत्पाद का नाम जोड़ें',
  'let_make_it':'चलो यह करते हैं',
  'what_my_name':'मेरा नाम क्या है? (मुख्य प्रस्ताव का नाम)',
  'offer_product':'उत्पाद पर प्रस्ताव',
  'all':'सभी',
  'specific':'विशिष्ट',
  'image':'छवि',
  'add':'+ जोड़ें',
  'unlimited':'असीमित',
  'select_gallery':'गैलरी का चयन करें',
  'select_camera':'कैमरा चुनें',
  'video':'वीडियो',

  //SideMenuScreen
  'my_subscription':'मेरी सदस्यता',
  'current_subscription':'वर्तमान सदस्यता',
  'refer_earn':'देखें और कमाएँ',
  'notification':'अधिसूचना',
  'redeem':'भुनाना',
  'help_faq':'सहायता और अक्सर पूछे जाने वाले प्रश्न',
  'entertainment':'मनोरंजन',
  'our_product':'हमारे उत्पाद',
  'history':'इतिहास',
  'event_offers':'मेरा कार्यक्रम और प्रस्ताव',
  'you_have':'आपके पास',
  'log_out':'लॉग आउट',
  'redeem_coin':'सिक्का भुनाएं',
  'redeem_your_coin':'अपना सिक्का भुनाएं',
  'redeem_des':'आपसे रिडीम की गई राशि का 5% शुल्क लिया जाएगा (\$12.35)',
  'enter_upi_id':'अपनी यूपीआई आईडी दर्ज करें',
  'upi_id':'यूपीआई आईडी',
  'coin_redeem':'सिक्का भुनाओ',
  'processing':'प्रसंस्करण',
  'login_refer':'लॉगिन संदर्भ',
  'coin_send':'सिक्का भेजें',
  'subcription_des':'आपके पास कोई सक्रिय सदस्यता नहीं है',
  'buy_now':'अभी खरीदें',

  //BuySubscriptionScreen
  'local_offer_month':'स्थानीय\nमासिक प्रस्ताव',
  'event_subscription':'इवेंट\nसदस्यता',
  'live_stream_subscription':'लाइव स्ट्रीम\nसदस्यता',
  'sub_des':'4 ईवेंट पोस्ट किया जा सकता है या अधिकतम 30 दिन के साथ एक ईवेंट',

  //MyEventOfferScreen
  'my_event_offers':'मेरे कार्यक्रम और प्रस्ताव',
  'event':'आयोजन',
  'offers':'ऑफर',

  //ReferAndEarnScreen
  'total_rewards_earned' : 'अर्जित कुल पुरस्कार',
  'refer_friends_earn' : 'अपने मित्रों को देखें\nऔर कमाएँ',
  'refer_get_coin' : 'रेफर करें और 10 कॉइन पाएं',
  'refer_earn_desc' : 'एक दोस्त को रेफर करें और अतिरिक्त 10 सिक्के प्राप्त करें और आपके दोस्त को अतिरिक्त 10 अंक मिलते हैं। इसलिए रेफर करें',
  'referral_code' : 'रेफरल कोड',
  'copy_code' : 'कॉपी\nकोड',
  'share_refer_code' : 'के माध्यम से अपना रेफर कोड साझा करें',

  //HelpAndFaqScreen
  'help' : 'मदद',
  'faq' : 'सामान्य प्रश्न',
  'evento_package' : 'इवेंटो पैकेज',
  'friends_fields':'फ्रेंड्स फील्ड्स',
  'fcoin':'एफ-सिक्का',
  'festum_ads_mdia':'फेस्टम विज्ञापन मीडिया',
  'evento_des' : 'लोरेम इप्सम के मार्ग के कई रूप उपलब्ध हैं, लेकिन अधिकांश ने किसी न किसी रूप में, इंजेक्ट किए गए हास्य, या यादृच्छिक शब्दों से बदलाव का सामना किया है जो थोड़ा सा भी विश्वसनीय नहीं लगता है।',

  //OnlineOfferAddScreen
  'choose_media_select':'चुनने के लिए मीडिया चुनें',
  'from_gallery':'गैलरी से',
  'from_camera':'कैमरा से',
  'online_shop_name':'ऑनलाइन दुकान का नाम',
  'offer':'प्रस्ताव',
  'product_name':'प्रोडक्ट का नाम',
  'add_offer_product_image':'प्रस्ताव उत्पाद छवि जोड़ें',
  'product_description':'उत्पाद वर्णन',
  'select_platform_product_link':'मंच और उत्पाद लिंक का चयन करें',
  'all_platform':'सभी प्लेटफार्म',

  //AddLiveStreamScreen
  'maximum_two_video_upload':'अधिकतम दो वीडियो अपलोड',
  'create_live_stream':'लाइव स्ट्रीम बनाएं',
  'event_name':'घटना नाम',
  'event_category':'घटना श्रेणी',
  'event_des':'घटना विवरण',
  'event_date':'कार्यक्रम की तिथि',
  'event_type':'घटना प्रकार',
  'free_for_user':'उपयोगकर्ता के लिए नि: शुल्क',
  'paid_for_user':'उपयोगकर्ता के लिए भुगतान किया',
  'join_live_streaming_price':'लाइव स्ट्रीमिंग मूल्य में शामिल हों',
  'per_user':'प्रति/उपयोगकर्ता',

  //MyEventAndOffers
  'view_invoice':'चालान देखें',
  'withdraw_amount':'राशि वापस ले',
  'invoice':'इनवॉइस',
  'invoice_no':'चालान नंबर :',
  'total_ticket_book':'कुल टिकट बुक किया गया',
  'sub_total':'उप कुल',
  'commission':'कमीशन (5%)',
  'gst':'जीएसटी',
  'payable_amount':'भुगतान योग्य राशि',
  'download_invoice':'इनवाइस को डाउनलोड करो',

  'enter_select_date':'चयन तिथि दर्ज करें',
  'enter_event_description':'घटना विवरण दर्ज करें',
  'enter_product_description':'उत्पाद विवरण दर्ज करें',
  'enter_product_name':'उत्पाद का नाम दर्ज करें',
  'enter_online_shop_name':'ऑनलाइन दुकान का नाम दर्ज करें',
  'enter_email_number': 'कृपया ईमेल या फोन नंबर दर्ज करें',
  'enter_password': 'कृपया पासवर्ड दर्ज करें',
  'enter_your_name': 'कृपया अपना नाम दर्ज करें',
  'enter_your_email': 'अपना ईमेल दर्ज करें',
  'enter_your_phone_number': 'कृपया अपना फोन नंबर दर्ज करें',
  'enter_your_confirm_password': 'कृपया अपना पुष्टि पासवर्ड दर्ज करें',
  'enter_your_refer_code': 'कृपया अपना कोड दर्ज करें',
  'enter_re_type_password': 'अपना पुनः टाइप पासवर्ड दर्ज करें',
  'enter_event_name': 'घटना का नाम दर्ज करें',
  'enter_other': 'अन्य दर्ज करें',
  'enter_start_time': 'प्रारंभ समय दर्ज करें',
  'enter_end_time': 'समाप्ति समय दर्ज करें',
  'enter_description': 'विवरण दर्ज करें',
  'enter_discount_total_bill': 'कुल बिल पर छूट दर्ज करें',
  'enter_terms_and_condition': 'नियम और शर्तें दर्ज करें',

  'enter_flat_no': 'फ्लैट नंबर दर्ज करें।',
  'enter_street_name': 'सड़क का नाम दर्ज करें',
  'enter_area_name': 'क्षेत्र का नाम दर्ज करें।',
  'enter_city': 'शहर में प्रवेश करें',
  'enter_state': 'राज्य दर्ज करें',
  'enter_pincode': 'पिनकोड दर्ज करें।',
  'enter_compuny_name': 'कंपनी का नाम दर्ज करें',
  'enter_company_contact_no': 'कंपनी का संपर्क नंबर दर्ज करें',
  'enter_company_email': 'कंपनी ईमेल दर्ज करें',
  'enter_about_our_company': 'हमारी कंपनी के बारे में दर्ज करें',
  'enter_full_name_mr': 'पूरा नाम दर्ज करें (श्री / श्रीमती / सुश्री)',
  'enter_mobile_number': 'मोबाइल नंबर दर्ज करें',
  'enter_alternative_mobile_number': 'वैकल्पिक मोबाइल नंबर दर्ज करें',
  'enter_email_address': 'ईमेल पता दर्ज करें',
  'enter_shop_name': 'दुकान का नाम दर्ज करें',
  'enter_about_us': 'हमारे बारे में दर्ज करें',
  'enter_offer_name': 'ऑफ़र का नाम डालें',
  'enter_no_of_table': 'तालिका की संख्या दर्ज करें',
  'enter_per_table_capacity': 'प्रति टेबल टरसन क्षमता दर्ज करें',
  'enter_total_person_capacity': 'कुल व्यक्ति क्षमता दर्ज करें',
  'enter_per_table_price': 'प्रति टेबल मूल्य दर्ज करें',
  'enter_per_person_price': 'प्रति व्यक्ति मूल्य दर्ज करें',
  'enter_total_amount': 'कुल राशि दर्ज करें',
  'enter_equipment_description': 'उपकरण विवरण दर्ज करें?',
  'enter_food_description': 'भोजन विवरण दर्ज करें',

  'enter_facebook_link': 'फेसबुक लिंक दर्ज करें',
  'enter_twitter_link': 'ट्विटर लिंक दर्ज करें',
  'enter_instagram_link': 'इंस्टाग्राम लिंक दर्ज करें',
  'enter_youtube_link': 'यूट्यूब लिंक दर्ज करें',
  'enter_pintrest_link': 'पिंटरेस्ट लिंक दर्ज करें',
  'enter_linkdin_link': 'लिंकडिन लिंक दर्ज करें',
};
