Map<String, String> us = {
  //LoginScreen
  'title_login': 'Hey, Login Now',
  'email_phone': 'Email or Phone number',
  'password': 'Password',
  'forget_password': 'Forget Password?',
  'login_now': 'Login Now',
  'are_you_new': 'Are you new?',
  'register_now': 'Register Now',

  //RegisterScreen
  'title_register': 'Create a new account',
  'your_name': 'Your Name',
  'email': 'Email',
  'phone_number': 'Phone Number',
  'confirm_password': 'Confirm Password',
  'refer_code': 'Refer Code',
  'optional': '(Optional)',
  'are_already_user': 'Are you already user?',
  'mobile_number_must_10_digit' : 'Mobile Number must be of 10 digit',
  'retry':'Retry',

  //ForgotPasswordScreen
  'forgot_password': 'Forgot Password',
  'send_otp': 'SEND OTP',

  //OtpScreen
  'enter_otp': 'Enter OTP',
  'verified': 'Verified',
  'not_get': 'Not Get?',
  're_send': ' Re-Send',
  're_send_otp': 'Re-Send Otp',

  //NewPasswordScreen
  'create_new_password': 'Create New Password',
  're_type_password': 'Re-Type Password',
  'save': 'Save',

  //DeshboardScreen
  'deshboard': 'Deshboard',
  'search': 'Search',
  'unverified': 'Unverified',
  'booking_accepting': 'Booking Accepting',

  //EventCategoryScreen
  'submit': 'Submit',
  'add_event': 'Add Event',
  'what_event_name': 'What’s event name?',
  'what_event_type': 'What’s the event type?',
  'b2b': 'B2B',
  'public_party': 'Public Party',
  'other': 'Other',

  //EventTimesScreen
  'select_start_date_end': 'Select start and end date',
  'back': 'Back',
  'next': 'Next',
  'create_new_event': 'Create New Event',
  'can_know_date': 'Can I know the dates?',
  'start_time': 'Start Time',
  'end_time': 'End Time',
  'event_description': 'What’s event description?',
  'select_date': 'Select Date',

  //EventSettingListScreen
  'select_any': 'Select Any',
  'let_create_it': 'Let’s Create it!',
  'no_of': 'No Of',
  'location' : 'Location',
  'no_of_person': 'No of Person',
  'price_table': 'Price / Table',
  'table': 'Table',
  'chair': 'Chair',
  'sofa': 'Sofa',
  'booth': 'Booth',
  'stands': 'Stands',
  'add_details': 'Add Details',
  'vettical_location': 'Vettical Location',
  'horizontal_location': 'Horizontal Location',
  'top': 'Top',
  'center': 'Center',
  'bottom': 'Bottom',
  'none': 'None',
  'left': 'Left',
  'right': 'Right',
  'per' : 'Per',
  'person_capacity': 'Person Capacity',
  'price': 'Price',
  'total_person_capacity': 'Total Person Capacity',
  'per_person_price': 'Per Person Price',
  'per_person' : 'Per Person',
  'total_amount': 'Total Amount',
  'veg': 'Veg',
  'non_veg': 'Non Veg',
  'both': 'Both',
  'non': 'Non',
  'select_food':'Select Food',
  'food_dexcription': 'Food description?',
  'select_Equipment': 'Select Equipment',
  'equipment': 'Equipment',
  'equipment_description': 'Equipment description?',
  'select_item': 'Select Item',
  'language_and_currency': 'Language and Currency',
  'add_cate' : 'Add',
  'food' : 'Food',

  //EventGalleryScreen
  'maximum_fifteen_images_upload': 'Maximum Fifteen Images Upload',
  'select_poster': 'Select Poster',
  'add_poster': 'Add Poster',
  'add_video': 'Add Video',
  'add_poster_15': 'Add Photos (Max 15)',
  'remove': 'REMOVE',
  'max_60min_video': 'Max 60min for 1 video',

  //EventPermissionLetterScreen
  'permission_verfication': 'Permission Letter for verification',
  'attached_pdf_only': 'Attached pdf only',
  'accept_booking': 'Accept Booking',
  'accept_booking_des':
      'Deselect it if you want to only show event and not allow user to book it',
  'des_1': 'For each ticket sold 6% Commission + GST will be Charged',
  'des_2': 'If the price of the ticket is 0 no commission will be Charged',

  //EventDiscountScreen
  'discount_total_bill': 'Discount on Total Bill',
  'cancel': 'CANCEL',
  'apply': 'APPLY',

  //EventAddressScreen
  'flat_no': 'Flat No.',
  'street_name': 'Street Name',
  'area_name': 'Area Name',
  'city': 'City',
  'state': 'State',
  'what_the_location': 'What’s the Location?',
  'type_here_address': 'Type here Address...',
  'location_from_google_map': 'Location from Google map',

  //EventCompanyDetailsScreen
  'maximum_one_video_upload': 'Maximum One Video Upload',
  'let_create_the_event': 'Let’s Create the Event',
  'company_name': 'Company Name',
  'company_gst': 'Company GST (Optional)',
  'upload_pdf': 'Upload PDF',
  'company_contact_no': 'Company Contact No',
  'company_email': 'Company Email',
  'about_our_company': 'About Our Company',
  'address': 'Address',
  'pincode': 'Pincode',
  'add_photo_max_05': 'Add Photos (Max 05)',
  'add_video_max_01': 'Add Video (Max 01)',

  //EventPersonalDetailsScreen
  'full_name_mr': 'Full Name (Mr / Mrs / Ms)',
  'mobile_number': 'Mobile Number',
  'alternative_mobile_number': 'Alternative Mobile Number (Optional)',
  'email_address': 'Email Address',

  //EventSocialMediaScreen
  'terms_and_condition': 'Terms and conditions',
  'social_media': 'Social Media',
  'accept_terms_and_condition': 'Accept Your Terms and Conditions',
  'live_this_event': 'Live This Event?',

  //CookingTogetherScreen
  'cooking_together': 'Cooking Together',
  'overview': 'OVERVIEW',
  'attendee': 'ATTENDEE',
  'review': 'REVIEW',

  //OverviewFragment
  'sold': 'Sold : ',
  'unsold': 'Unsold : ',
  'check': 'CHECK',
  'food_description': 'Food Description',
  'photo_video_gallery': 'Photo & Video Gallery',
  'ticket': 'Ticket',
  'price': 'Price',
  'show_all': 'Show all',

  //ShopFragment
  'shop_offer': 'Shop Offer',
  'online_offer': 'Online Offer',
  'add_your_shop': 'Add Your Shop',
  'create_offer': 'Create Offer',

  //ShopAddScreen
  'continue': 'CONTINUE',
  'let_add_shop': 'Let’s Add Shop!',
  'select_category': 'Select Category',
  'shop_name': 'Shop Name',
  'shop_day': 'Shop Day',
  'about_us': 'About Us',
  'social_media_link': 'Social Media Links',

  //ShopDetailsScreen
  'edit':'Edit',
  'show':'Show',
  'delete':'Delete',
  'about_shop':'About Shop',

  //OfferAddScreen
  'person':'Person',
  'percentage':'Percentage',
  'description':'Description',
  'image_add':'Add\nImage',
  'add_products_name':'Add Products Name',
  'let_make_it':'Let’s Make it',
  'what_my_name':'What’s my name? (Main offer name)',
  'offer_product':'Offer on Product',
  'all':'All',
  'specific':'Specific',
  'image':'Image',
  'add':'+ Add',
  'unlimited':'Unlimited',
  'select_gallery':'Select Gallery',
  'select_camera':'Select Camera',
  'video':'Video',

  //SideMenuScreen
  'my_subscription':'My Subscription',
  'current_subscription':'Current Subscription',
  'refer_earn':'Refer and Earn',
  'notification':'Notification',
  'redeem':'Redeem',
  'help_faq':'Help & FAQ',
  'entertainment':'Entertainment',
  'our_product':'Our Product',
  'history':'History',
  'event_offers':'My Event & Offers',
  'you_have':'You Have',
  'log_out':'LOG OUT',
  'redeem_coin':'Redeem Coin',
  'redeem_your_coin':'Redeem Your Coin',
  'redeem_des':'You will be charge 5% of amount you redeem (\$12.35)',
  'enter_upi_id':'Enter Your Upi id',
  'upi_id':'UPI ID',
  'coin_redeem':'Coin Redeem',
  'processing':'Processing',
  'login_refer':'Login Refer',
  'coin_send':'Coin Send',
  'subcription_des':'You don’t have any active subscription',
  'buy_now':'BUY NOW',

  //BuySubscriptionScreen
  'local_offer_month':'Local\nOffer Monthly',
  'event_subscription':'Event\nSubscription',
  'live_stream_subscription':'Live Stream\nSubscription',
  'sub_des':'4 Event can be posted or one event with max 30 day',

  //MyEventOfferScreen
  'my_event_offers':'My Events & Offers',
  'event':'Events',
  'offers':'Offers',

  //ReferAndEarnScreen
  'total_rewards_earned' : 'Total Rewards Earned',
  'refer_friends_earn' : 'Refer to your Friends\nand Earn',
  'refer_get_coin' : 'Refer and Get 10 Coin',
  'refer_earn_desc' : 'Refer a friend and get an additional 10 coins and your friend gets additional 10 point.So Refer away',
  'referral_code' : 'Referral Code',
  'copy_code' : 'Copy\nCode',
  'share_refer_code' : 'Share your refer code via',

  //HelpAndFaqScreen
  'help' : 'Help',
  'faq' : 'FAQ',
  'evento_package' : 'Evento Package',
  'friends_fields':'Friends Fields',
  'fcoin':'F-Coin',
  'festum_ads_mdia':'Festum Advertising Media',
  'evento_des' : 'There Are Many Variations Of Passages Of Lorem Ipsum Available, But The Majority Have Suffered Alteration In Some Form, By Injected Humour, Or Randomised Words Which Don\'t Look Even Slightly Believable.',

  //OnlineOfferAddScreen
  'choose_media_select':'Choose media to select',
  'from_gallery':'From Gallery',
  'from_camera':'From Camera',
  'online_shop_name':'Online shop Name',
  'offer':'Offer',
  'product_name':'Product Name',
  'add_offer_product_image':'Add Offer Product Image',
  'product_description':'Product Description',
  'select_platform_product_link':'Select platform & product link',
  'all_platform':'All Platform',

  //AddLiveStreamScreen && SocialMedia
  'maximum_two_video_upload':'Maximum Two Video Upload',
  'create_live_stream':'Create Live Stream',
  'event_name':'Event Name',
  'event_category':'Event Category',
  'event_des':'Event Description',
  'event_date':'Event Date',
  'event_type':'Event Type',
  'free_for_user':'Free for user',
  'paid_for_user':'Paid for user',
  'join_live_streaming_price':'Join live streaming price',
  'per_user':'Per/User',

  //MyEventAndOffers
  'view_invoice':'VIEW INVOICE',
  'withdraw_amount':'Withdraw Amount',
  'invoice':'Invoice',
  'invoice_no':'Invoice No : ',
  'total_ticket_book':'Total Ticket Booked',
  'sub_total':'Sub Total',
  'commission':'Commission (5%)',
  'gst':'GST',
  'payable_amount':'Payable Amount',
  'download_invoice':'Download Invoice',

  'enter_select_date':'Enter Select Date',
  'enter_event_description':'Enter Event Description',
  'enter_product_description':'Enter Product Description',
  'enter_product_name':'Enter Product Name',
  'enter_online_shop_name':'Enter Online shop Name',
  'enter_email_number': 'Please enter email or phone number',
  'enter_password': 'Please your enter password',
  'enter_your_name': 'Please enter your name',
  'enter_your_email': 'Please enter your email',
  'enter_your_phone_number': 'Please enter your phone number',
  'enter_your_confirm_password': 'Please enter your confirm password',
  'enter_your_refer_code': 'Please enter your code',
  'enter_re_type_password': 'Enter your re-type password',
  'enter_event_name': 'Enter Event Name',
  'enter_other': 'Enter Other',
  'enter_start_time': 'Enter Start Time',
  'enter_end_time': 'Enter End Time',
  'enter_description': 'Enter Description',
  'enter_discount_total_bill': 'Enter Discount On Total Bill',
  'enter_terms_and_condition': 'Enter Terms & Conditions',

  'enter_flat_no': 'Enter Flat No.',
  'enter_street_name': 'Enter Street Name',
  'enter_area_name': 'Enter Area Name.',
  'enter_city': 'Enter City',
  'enter_state': 'Enter State',
  'enter_pincode': 'Enter Pincode',
  'enter_compuny_name': 'Enter Company Name',
  'enter_company_contact_no': 'Enter Company Contact No',
  'enter_company_email': 'Enter Company Email',
  'enter_about_our_company': 'Enter About Our Company',
  'enter_full_name_mr': 'Enter Full Name (Mr / Mrs / Ms)',
  'enter_mobile_number': 'Enter Mobile Number',
  'enter_alternative_mobile_number': 'Enter Alternative Mobile Number',
  'enter_email_address': 'Enter Email Address',
  'enter_shop_name': 'Enter Shop Name',
  'enter_about_us': 'Enter About Us',
  'enter_offer_name': 'Enter Offer Name',
  'enter_no_of_table': 'Enter No Of ',
  'enter': 'Enter ',
  'enter_total_person_capacity': 'Enter Total person capacity',
  'enter_per_table_price': 'Enter Per Table Price',
  'enter_per_person_price': 'Enter Per Person Price',
  'enter_total_amount': 'Enter Total Amount',
  'enter_equipment_description': 'Enter Equipment description?',
  'enter_food_description': 'Enter Food Description',

  'enter_facebook_link': 'Enter Facebook Link',
  'enter_twitter_link': 'Enter Twitter Link',
  'enter_instagram_link': 'Enter Instagram Link',
  'enter_youtube_link': 'Enter Youtube Link',
  'enter_pintrest_link': 'Enter Pintrest Link',
  'enter_linkdin_link': 'Enter Linkdin Link',
};
